import asyncio
from sqlalchemy import select
from src.database.database import session
from src.database.models.players import Player , PlayerRoleEnum
from src.database.models.teams import Team


main_players = {
    'parivision': [
        Player(
            nickname="Jame",
            real_name="Джами Али",
            country_code="RU",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="BELCHONOKK",
            real_name="Андрей Ясинский",
            country_code="RU",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="xiELO",
            real_name="Владислав Лысов",
            country_code="RU",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="nota",
            real_name="Эмиль Москвитин",
            country_code="RU",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="zweih",
            real_name="Иван Гогин",
            country_code="RU",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'team-falcons': [
        Player(
            nickname="NiKo",
            real_name="Никола Ковач",
            country_code="BA",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="TeSeS",
            real_name="Рене Мадсен",
            country_code="DK",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="m0NESY",
            real_name="Илья Осипов",
            country_code="RU",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="kyxsan",
            real_name="Дамьян Стоилковски",
            country_code="MK",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="kyousuke",
            real_name="Максим Лукин",
            country_code="RU",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'team-spirit': [
        Player(
            nickname="donk",
            real_name="Данил Крышковец",
            country_code="RU",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="zont1x",
            real_name="Мирослав Плахотя",
            country_code="UA",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="magixx",
            real_name="Борис Воробьёв",
            country_code="RU",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="sh1ro",
            real_name="Дмитрий Соколов",
            country_code="RU",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="tN1R",
            real_name="Андрей Татаринович",
            country_code="BY",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'g2-esports': [
        Player(
            nickname="huNter-",
            real_name="Неманья Ковач",
            country_code="BA",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="HeavyGod",
            real_name="Никита Мартыненко",
            country_code="IL",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="SunPayus",
            real_name="Альваро Гарсия",
            country_code="ES",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="MATYS",
            real_name="Матуш Шимко",
            country_code="SK",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="NertZ",
            real_name="Гай Илуз",
            country_code="IL",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'the-mongolz': [
        Player(
            nickname="bLitz",
            real_name="Гаридмагнай Бямбасурэн",
            country_code="MN",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Techno",
            real_name="Содбаяр Мунхболд",
            country_code="MN",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="mzinho",
            real_name="Аюш Батболд",
            country_code="MN",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="910",
            real_name="Усухбаяр Банзрагч",
            country_code="MN",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="cobrazera",
            real_name="Отгонлхагва Батжаргал",
            country_code="MN",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'mouz': [
        Player(
            nickname="Brollan",
            real_name="Людвиг Бролин",
            country_code="SE",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Jimpphat",
            real_name="Йими Сало",
            country_code="FI",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Spinx",
            real_name="Лотан Гилади",
            country_code="IL",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="torzsi",
            real_name="Адам Торжаш",
            country_code="HU",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="xertioN",
            real_name="Дориан Берман",
            country_code="IL",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'furia': [
        Player(
            nickname="FalleN",
            real_name="Габриэль Толедо",
            country_code="BR",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="KSCERATO",
            real_name="Кайке Керато",
            country_code="BR",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="molodoy",
            real_name="Данил Голубенко",
            country_code="KZ",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="YEKINDAR",
            real_name="Марекс Галинскис",
            country_code="LV",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="yuurih",
            real_name="Юрий Сантос",
            country_code="BR",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'aurora-gaming': [
        Player(
            nickname="MAJ3R",
            real_name="Энгин Кюпели",
            country_code="TR",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="XANTARES",
            real_name="Исмаилджан Дёрткардеш",
            country_code="TR",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="woxic",
            real_name="Озгюр Экер",
            country_code="TR",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="soulfly",
            real_name="Джанер Кесичи",
            country_code="TR",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Wicadia",
            real_name="Али Хайдар Ялчын",
            country_code="TR",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'heroic': [
        Player(
            nickname="xfl0ud",
            real_name="Ясин Коч",
            country_code="TR",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="nilo",
            real_name="Линус Бергман",
            country_code="SE",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="susp",
            real_name="Тим Онгстрём",
            country_code="SE",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Chr1zN",
            real_name="Кристоффер Сторгор",
            country_code="DK",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Alkaren",
            real_name="Алимжан Битимбай",
            country_code="KZ",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'gentle-mates': [
        Player(
            nickname="alex",
            real_name="Алехандро Масанет",
            country_code="ES",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="mopoz",
            real_name="Алехандро Фернандес-Кехо Кано",
            country_code="ES",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="sausol",
            real_name="Сауль Кастаньо",
            country_code="ES",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="dav1g",
            real_name="Давид Гранде",
            country_code="ES",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="MartinezSa",
            real_name="Антонио Мартинес",
            country_code="ES",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'monte': [
        Player(
            nickname="Rainwaker",
            real_name="Любослав Панайотов",
            country_code="BG",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Bymas",
            real_name="Ауримас Пипирас",
            country_code="LT",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="afro",
            real_name="Орельен Драпье",
            country_code="FR",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Gizmy",
            real_name="Мартин Вражнов",
            country_code="BG",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="AZUWU",
            real_name="Кристиан Янков",
            country_code="BG",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'fut-esports': [
        Player(
            nickname="dem0n",
            real_name="Дамьян Христов",
            country_code="BG",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="lauNX",
            real_name="Лауренциу Цырля",
            country_code="RO",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Krabeni",
            real_name="Кристиан Станчев",
            country_code="BG",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="cmtry",
            real_name="Кристиян Митев",
            country_code="BG",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="dziugss",
            real_name="Джюгас Степонавичюс",
            country_code="LT",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],
}


async def sync_players(teams, s):
    for team in teams:
        new_players = main_players.get(team.slug, [])

        result = await s.execute(
            select(Player).where(Player.team_id == team.id)
        )
        db_players = result.scalars().all()

        db_players_map = {p.nickname: p for p in db_players}
        new_nicknames = {player.nickname for player in new_players}

        for new_player in new_players:
            existing = db_players_map.get(new_player.nickname)

            if existing:
                existing.real_name = new_player.real_name
                existing.country_code = new_player.country_code
                existing.role = new_player.role
                existing.is_active = True
            else:
                new_player.team_id = team.id
                new_player.is_active = True
                s.add(new_player)

        for db_player in db_players:
            if db_player.nickname not in new_nicknames:
                db_player.is_active = False

    await s.commit()


async def main():
    async with session() as s:
        result = await s.execute(select(Team))
        teams = result.scalars().all()

        await sync_players(teams, s)



if __name__ == '__main__':
    asyncio.run(main())