import asyncio
from sqlalchemy import select
from src.database.database import session
from src.database.models.players import Player , PlayerRoleEnum
from src.database.models.teams import Team
from src.database.models.matches import PlayerStats


main_players = {
    'parivision': [
        Player(
            nickname="Jame",
            real_name="Джами Али",
            country_code="RU",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/13776/jame",
            description='Джами “Jame” Али — один из самых узнаваемых капитанов и AWP-игроков современной сцены. Его стиль — это контроль темпа, дисциплина и холодный расчёт, благодаря которым он привёл Outsiders к победе на мейджоре и закрепился в истории CS как MVP крупнейшего турнира. Jame умеет выигрывать не за счёт хаоса, а за счёт идеального понимания экономики, позиций и таймингов. В PARIVISION он остаётся центром системы: вокруг его решений строится игра команды, а его стабильность и опыт позволяют коллективу конкурировать с сильнейшими соперниками.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="BELCHONOKK",
            real_name="Андрей Ясинский",
            country_code="RU",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19235/belchonokk",
            description='Андрей “BELCHONOKK” Ясинский — молодой rifler, который постепенно закрепляется на профессиональной сцене. Его игра строится на дисциплине и понимании командных ролей: он не стремится к хайлайтам, но стабильно выполняет задачи, необходимые для победы. Участие в матчах против более сильных соперников даёт ему опыт тир-1 уровня, а в составе PARIVISION он получает возможность расти рядом с такими игроками, как Jame. Его потенциал заметен в уверенной стрельбе и способности адаптироваться к темпу игры команды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="xiELO",
            real_name="Владислав Лысов",
            country_code="RU",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/22471/xielo",
            description='Владислав “xiELO” Лысов — rifler, играющий важную роль в структуре PARIVISION. Он отвечает за удержание позиций, грамотные размены и стабильность в ключевых раундах. Его вклад часто остаётся “за кадром”, но именно такие игроки позволяют команде держать баланс между агрессией и контролем. Участие в международных матчах и регулярная практика против сильных соперников помогают ему постепенно закрепляться на высоком уровне и развиваться внутри системы команды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="nota",
            real_name="Эмиль Москвитин",
            country_code="RU",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/22929/nota",
            description='Эмиль “nota” Москвитин — support-игрок, который обеспечивает дисциплину и порядок в игре команды. Его задачи включают контроль карты, помощь в разменах и создание условий для звёздных игроков. Nota играет важную роль в реализации стратегий капитана, позволяя команде действовать слаженно даже в напряжённых ситуациях. Его вклад особенно заметен в матчах, где важна структура и минимизация ошибок, что критично для выступлений на серьёзных турнирах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="zweih",
            real_name="Иван Гогин",
            country_code="RU",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/23685/zweih",
            description='Иван “zweih” Гогин — перспективный rifler, добавляющий команде огневую мощь и агрессию. Его стиль сочетает уверенную стрельбу и готовность брать на себя инициативу в сложных ситуациях. Выступая на профессиональной сцене, он постепенно набирает опыт и учится играть против топовых соперников. В составе PARIVISION он является важной частью роста команды, дополняя более опытных игроков и усиливая общий потенциал коллектива.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'team-falcons': [
        Player(
            nickname="NiKo",
            real_name="Никола Ковач",
            country_code="BA",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/3741/niko",
            description='Никола “NiKo” Ковач — один из величайших rifler в истории Counter-Strike. За свою карьеру он выступал за топ-организации, включая FaZe и G2, выигрывал крупные турниры и неоднократно входил в топ игроков мира по версии HLTV. Его механика, aim и понимание игры сделали его эталоном для rifler-игроков. В составе Falcons он приносит не только огневую мощь, но и огромный опыт тир-1 сцены.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="TeSeS",
            real_name="Рене Мадсен",
            country_code="DK",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/12018/teses",
            description='Рене “TeSeS” Мадсен — опытный rifler, известный по выступлениям за Heroic, где он выигрывал крупные турниры и стабильно играл на тир-1 уровне. Его стиль игры отличается надёжностью и способностью выполнять сложные роли в команде. В составе Falcons он приносит стабильность, опыт и понимание игры на высшем уровне.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="m0NESY",
            real_name="Илья Осипов",
            country_code="RU",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19230/m0nesy",
            description='Илья “m0NESY” Осипов — один из самых талантливых снайперов нового поколения. Ещё в составе NAVI Junior он привлёк внимание своей агрессивной и уверенной игрой, после чего перешёл в G2, где быстро стал ключевым игроком. Он регулярно показывает хайлайты мирового уровня и уже выигрывал крупные турниры. Его стиль сочетает в себе агрессию, скорость реакции и нестандартные решения.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="kyxsan",
            real_name="Дамьян Стоилковски",
            country_code="MK",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19677/kyxsan",
            description='Дамьян “kyxsan” Стоилковски — капитан и стратег команды, отвечающий за игровую структуру и принятие решений. Несмотря на сравнительно меньший опыт на тир-1 уровне, он уже показал способность вести команду и адаптироваться к сильным соперникам. Его роль особенно важна в построении командной игры и развитии состава.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="kyousuke",
            real_name="Максим Лукин",
            country_code="RU",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/24177/kyousuke",
            description='Максим “kyousuke” Лукин — молодой и перспективный игрок, который только начинает свой путь на профессиональной сцене. Несмотря на возраст, он уже показывает уверенную игру и быстро адаптируется к уровню тир-1 матчей. Его потенциал делает его важной частью будущего команды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'team-spirit': [
        Player(
            nickname="donk",
            real_name="Данил Крышковец",
            country_code="RU",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/21167/donk",
            description='Данил “donk” Крышковец — один из самых ярких молодых талантов современной CS-сцены. Его агрессивный стиль entry-фраггера и феноменальный aim сделали его ключевым фактором доминации Team Spirit на международных турнирах. Уже в раннем возрасте он начал показывать уровень, сравнимый с топ-игроками мира, регулярно решая раунды в одиночку. Его вклад в победы команды и глубокие проходы на крупных ивентах закрепил за ним статус будущей суперзвезды сцены.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="zont1x",
            real_name="Мирослав Плахотя",
            country_code="UA",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20423/zont1x",
            description='Мирослав “zont1x” Плахотя — универсальный игрок, выполняющий ключевые support-функции в составе Team Spirit. Его задача — создавать пространство для звёзд команды, обеспечивать контроль карты и поддерживать структуру раундов. Несмотря на менее заметную роль, именно такие игроки делают возможными победы на высоком уровне, особенно в матчах против топ-команд мировой сцены.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="magixx",
            real_name="Борис Воробьёв",
            country_code="RU",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/18317/magixx",
            description='Борис “magixx” Воробьёв — важнейший элемент системы Team Spirit, сочетающий в себе опыт, дисциплину и гибкость. В роли IGL он помогает команде принимать правильные решения в сложных игровых ситуациях, контролируя темп и структуру раундов. Его вклад не всегда выражается в статистике, но именно за счёт таких игроков команды выигрывают крупные турниры и стабильно держатся на тир-1 уровне.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="sh1ro",
            real_name="Дмитрий Соколов",
            country_code="RU",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/16920/sh1ro",
            description='Дмитрий “sh1ro” Соколов — один из самых стабильных снайперов в мире CS. Его стиль игры отличается холодной расчетливостью, минимальным количеством ошибок и невероятной эффективностью в клатч-ситуациях. Ранее он был ключевым игроком Cloud9, с которыми выигрывал крупные турниры и стабильно входил в топ HLTV. В составе Team Spirit он усилил команду, добавив ей стабильность и контроль в решающих моментах матчей.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="tN1R",
            real_name="Андрей Татаринович",
            country_code="BY",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19808/tn1r",
            description='Андрей “tN1R” Татаринович — стабильный rifler, усиливающий состав Team Spirit своей дисциплинированной и надёжной игрой. Он не стремится к ярким хайлайтам, но регулярно выполняет свою роль на высоком уровне, обеспечивая команде баланс и стабильность. Его вклад особенно заметен в долгих сериях и напряжённых матчах против сильнейших соперников.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'g2-esports': [
        Player(
            nickname="huNter-",
            real_name="Неманья Ковач",
            country_code="BA",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/3972/hunter",
            description='Неманья “huNter-” Ковач — один из самых стабильных rifler на тир-1 сцене. За годы в G2 он участвовал в победах на крупных турнирах и стабильно показывал высокий уровень. Его опыт и стрельба делают его ключевым игроком команды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="HeavyGod",
            real_name="Никита Мартыненко",
            country_code="IL",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20447/heavygod",
            description='Никита “HeavyGod” Мартыненко — молодой талант, который быстро адаптировался к тир-1 уровню. Он усиливает состав G2 своей агрессией и уверенностью в дуэлях.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="SunPayus",
            real_name="Альваро Гарсия",
            country_code="ES",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19164/sunpayus",
            description='Альваро “SunPayus” Гарсия — AWP-игрок высокого уровня, известный по выступлениям за ENCE. Он стабильно показывает результат на международной сцене и приносит команде важные фраги.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="MATYS",
            real_name="Матуш Шимко",
            country_code="SK",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/21062/matys",
            description='Матуш “MATYS” Шимко — перспективный entry-фраггер, усиливающий темп игры команды. Его агрессивный стиль позволяет G2 создавать давление.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="NertZ",
            real_name="Гай Илуз",
            country_code="IL",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/9436/nertz",
            description='Гай “NertZ” Илуз — rifler с опытом тир-1 сцены, ранее выступал за ENCE и другие команды, показывая стабильный уровень.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'the-mongolz': [
        Player(
            nickname="bLitz",
            real_name="Гаридмагнай Бямбасурэн",
            country_code="MN",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20194/blitz",
            description='Гаридмагнай “bLitz” Бямбасурэн — капитан и лидер MongolZ, сыгравший ключевую роль в выходе команды на международную сцену. Под его руководством коллектив стабильно участвует в крупных турнирах и квалификациях, представляя Азию на тир-1 уровне.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Techno",
            real_name="Содбаяр Мунхболд",
            country_code="MN",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20275/techno",
            description='Содбаяр “Techno” Мунхболд — support-игрок, обеспечивающий структуру и баланс команды. Он играет важную роль в удержании позиций и создании пространства для тиммейтов, помогая MongolZ конкурировать с более опытными составами.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="mzinho",
            real_name="Аюш Батболд",
            country_code="MN",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/21001/mzinho",
            description='Аюш “mzinho” Батболд — молодой rifler, демонстрирующий быстрый рост на профессиональной сцене. Его агрессивная игра и уверенность позволяют команде бороться с соперниками на международных турнирах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="910",
            real_name="Усухбаяр Банзрагч",
            country_code="MN",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/21809/910",
            description='Усухбаяр “910” Банзрагч — снайпер команды, отвечающий за ключевые фраги в решающих моментах. Его игра помогает MongolZ закрепляться на сцене и выходить на крупные турниры.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="cobrazera",
            real_name="Отгонлхагва Батжаргал",
            country_code="MN",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/23402/cobrazera",
            description='Отгонхжаргал “cobrazera” Батжаргал — entry-фраггер, создающий давление на соперников. Его агрессивный стиль помогает команде выигрывать важные раунды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'mouz': [
        Player(
            nickname="Brollan",
            real_name="Людвиг Бролин",
            country_code="SE",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/13666/brollan",
            description='Людвиг “Brollan” Бролин — опытный rifler, известный по выступлениям за Fnatic и другим тир-1 командам. Он участвовал в мейджорах и крупных турнирах, где стабильно показывал высокий уровень стрельбы. В составе MOUZ он приносит опыт и уверенность, помогая команде бороться с сильнейшими соперниками на международной сцене.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Jimpphat",
            real_name="Йими Сало",
            country_code="FI",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/18850/jimpphat",
            description='Йими “Jimpphat” Сало — один из самых перспективных молодых игроков Европы. Несмотря на возраст, он уже демонстрирует зрелую игру, отличное понимание позиций и стабильную стрельбу. Его быстрое развитие и уверенность делают его важной частью будущего MOUZ.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Spinx",
            real_name="Лотан Гилади",
            country_code="IL",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/18221/spinx",
            description='Лотан “Spinx” Гилади — rifler мирового уровня, ранее блиставший в ENCE и Vitality. Он участвовал в победах на крупных турнирах и стабильно входил в число сильнейших игроков по статистике. Его стабильность и умение играть в сложных ситуациях делают его ключевым элементом команды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="torzsi",
            real_name="Адам Торжаш",
            country_code="HU",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/18072/torzsi",
            description='Адам “torzsi” Торжаш — основной AWP команды, отвечающий за контроль и стабильные фраги. Его игра помогает MOUZ удерживать позиции в матчах против топ-команд, а опыт выступлений на крупных турнирах укрепляет его статус на сцене.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="xertioN",
            real_name="Дориан Берман",
            country_code="IL",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20312/xertion",
            description='Дориан “xertioN” Берман — агрессивный rifler, создающий давление и пространство для команды. Его стиль игры делает его опасным в дуэлях, а вклад в атакующие действия помогает MOUZ диктовать темп матчей.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'furia': [
        Player(
            nickname="FalleN",
            real_name="Габриэль Толедо",
            country_code="BR",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/2023/fallen",
            description='Габриэль “FalleN” Толедо — легенда Counter-Strike и двукратный чемпион мейджоров. Его вклад в развитие сцены огромен: он не только выигрывал крупнейшие турниры, но и сформировал стиль игры бразильских команд. В составе FURIA он приносит опыт, лидерство и стратегическое мышление.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="KSCERATO",
            real_name="Кайке Керато",
            country_code="BR",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/15631/kscerato",
            description='Кайке “KSCERATO” Керато — один из самых стабильных rifler мира. На протяжении нескольких лет он входит в число лучших игроков по версии HLTV, демонстрируя высокий уровень стрельбы и понимания игры. Его стабильность делает его ключевым игроком FURIA.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="molodoy",
            real_name="Данил Голубенко",
            country_code="KZ",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/24144/molodoy",
            description='Данил “molodoy” Голубенко — молодой игрок, который постепенно закрепляется на профессиональной сцене. Его уверенная игра и стремление развиваться делают его перспективным элементом состава.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="YEKINDAR",
            real_name="Марекс Галинскис",
            country_code="LV",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/13915/yekindar",
            description='Марекс “YEKINDAR” Галинскис — один из самых агрессивных entry-фраггеров в мире. Ранее он блистал в Virtus.pro и Liquid, где показывал высокий impact и помогал командам достигать успеха на крупных турнирах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="yuurih",
            real_name="Юрий Сантос",
            country_code="BR",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/12553/yuurih",
            description='Юрий “yuurih” Сантос — стабильный rifler, который на протяжении многих лет остаётся ключевым игроком FURIA. Его вклад в результаты команды и выступления на крупных турнирах делает его одним из лидеров состава.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'aurora': [
        Player(
            nickname="MAJ3R",
            real_name="Энгин Кюпели",
            country_code="TR",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/150/maj3r",
            description='Энгин “MAJ3R” Кюпели — опытный капитан и лидер турецкой сцены. Он много лет выступает на международных турнирах и ведёт команды на высокий уровень.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="XANTARES",
            real_name="Исмаилджан Дёрткардеш",
            country_code="TR",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/7938/xantares",
            description='Исмаилджан “XANTARES” Дёрткардеш — легендарный aim-игрок, известный своей механикой и доминацией на HLTV. Один из самых опасных rifler мира.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="woxic",
            real_name="Озгюр Экер",
            country_code="TR",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/8574/woxic",
            description='Озгюр “woxic” Экер — агрессивный AWP-игрок, ранее выступал за mousesports и показывал высокий уровень на тир-1 турнирах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="soulfly",
            real_name="Джанер Кесичи",
            country_code="TR",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20968/soulfly",
            description='Джанер “soulfly” Кесичи — support-игрок, обеспечивающий баланс команды и стабильность в раундах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Wicadia",
            real_name="Али Хайдар Ялчын",
            country_code="TR",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/21243/wicadia",
            description='Али “Wicadia” Хайдар Ялчин — молодой rifler, быстро развивающийся и усиливающий состав Aurora.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'heroic': [
        Player(
            nickname="xfl0ud",
            real_name="Ясин Коч",
            country_code="TR",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19187/xfl0ud",
            description='Ясин “xfl0ud” Коч — rifler, постепенно закрепляющийся на международной сцене и набирающий опыт в матчах против сильных соперников. Его игра строится на дисциплине, понимании позиций и умении поддерживать команду в сложных ситуациях. Несмотря на относительно небольшой опыт тир-1, он уже демонстрирует уверенность в стрельбе и способность адаптироваться к высокому темпу игры, что делает его важным элементом обновлённого состава Heroic.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="nilo",
            real_name="Линус Бергман",
            country_code="SE",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20119/nilo",
            description='Линус “nilo” Бергман — один из самых перспективных молодых игроков Европы, привлекающий внимание своим хладнокровием и стабильностью. Его стиль сочетает аккуратную стрельбу и грамотное позиционирование, что позволяет ему уверенно выступать даже против более опытных соперников. В составе Heroic он получает возможность развиваться на высоком уровне, постепенно раскрывая свой потенциал на международной сцене.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="susp",
            real_name="Тим Онгстрём",
            country_code="SE",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/21163/susp",
            description='Тим “susp” Онгстрём — support-игрок, выполняющий важную роль в структуре команды. Его задачи включают контроль карты, помощь в разменах и обеспечение стабильности в раундах. Такие игроки редко попадают в хайлайты, но именно благодаря их работе команда способна действовать слаженно и эффективно, особенно в матчах против сильных соперников на крупных турнирах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Chr1zN",
            real_name="Кристоффер Сторгор",
            country_code="DK",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/21983/chr1zn",
            description='Кристоффер “Chr1zN” Сторгор — rifler, усиливающий огневую мощь команды и способный брать на себя инициативу в ключевых моментах. Его игра отличается агрессией и уверенностью, что помогает Heroic создавать давление на соперника. Участие в международных матчах позволяет ему набирать опыт и постепенно закрепляться на более высоком уровне.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Alkaren",
            real_name="Алимжан Битимбай",
            country_code="KZ",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/23600/alkaren",
            description='Алимжан “Alkaren” Битимбай — представитель Казахстана на профессиональной сцене, что уже делает его заметной фигурой для региональных болельщиков. Его игра строится на стремлении развиваться и адаптироваться к требованиям современной CS-сцены. В составе Heroic он получает опыт игры против сильных соперников, что способствует его росту как профессионального игрока.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'gentle-mates': [
        Player(
            nickname="alex",
            real_name="Алехандро Масанет",
            country_code="ES",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/8371/alex",
            description='Александро “alex” Масанет — опытный капитан, выступавший на мейджорах и крупных турнирах. Известен своим лидерством и пониманием игры.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="mopoz",
            real_name="Алехандро Фернандес-Кехо Кано",
            country_code="ES",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/9254/mopoz",
            description='Алехандро “mopoz” Фернандес — rifler с опытом международных турниров, стабильно выступает на сцене.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="sausol",
            real_name="Сауль Кастаньо",
            country_code="ES",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/18749/sausol",
            description='Сауль “sausol” Кастаньо — молодой игрок, демонстрирующий рост и потенциал.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="dav1g",
            real_name="Давид Гранде",
            country_code="ES",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19509/dav1g",
            description='Давид “dav1g” Гранде — support-игрок, обеспечивающий структуру команды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="MartinezSa",
            real_name="Антонио Мартинес",
            country_code="ES",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/21239/martinezsa",
            description='Антонио “MartinezSa” Мартинес — AWP-игрок, ключевой элемент команды в решающих раундах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'monte': [
        Player(
            nickname="Rainwaker",
            real_name="Любослав Панайотов",
            country_code="BG",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/17145/rainwaker",
            description='Любослав “Rainwaker” Панайотов — опытный rifler, выступавший на мейджорах и крупных международных турнирах. Его игра отличается стабильностью и пониманием командных ролей, что делает его важным элементом состава Monte. Он способен удерживать позиции, грамотно размениваться и сохранять контроль в сложных раундах, что особенно важно на высоком уровне конкуренции.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Bymas",
            real_name="Ауримас Пипирас",
            country_code="LT",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19015/bymas",
            description='Ауримас “Bymas” Пипирас — игрок с опытом выступлений за FaZe Clan, где он участвовал в матчах против сильнейших команд мира. Этот опыт тир-1 сцены сформировал его как универсального rifler, способного адаптироваться к разным ролям. В Monte он приносит не только огневую мощь, но и понимание того, как играть на высоком уровне против топовых соперников.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="afro",
            real_name="Орельен Драпье",
            country_code="FR",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19926/afro",
            description='Орельен “afro” Драпье — AWP-игрок, известный своей стабильной игрой на европейской сцене. Его стиль сочетает аккуратность и уверенность, что позволяет ему регулярно приносить команде важные фраги. В составе Monte он играет ключевую роль в удержании позиций и контроле раундов, особенно в защите.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Gizmy",
            real_name="Мартин Вражнов",
            country_code="BG",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/21816/gizmy",
            description='Мартин “Gizmy” Вражнов — молодой игрок, демонстрирующий постепенный рост и развитие на профессиональной сцене. Его участие в международных матчах помогает ему набирать опыт, а уверенная стрельба и стремление к развитию делают его перспективным элементом команды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="AZUWU",
            real_name="Кристиан Янков",
            country_code="BG",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/22106/azuwu",
            description='Кристиан “AZUWU” Янков — rifler, который дополняет состав Monte своей стабильной игрой и командной дисциплиной. Он выполняет важные роли в раундах, помогая удерживать баланс между агрессией и контролем. Его вклад особенно заметен в долгих матчах, где важна стабильность и минимизация ошибок.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'fut-esports': [
        Player(
            nickname="dem0n",
            real_name="Дамьян Христов",
            country_code="BG",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20584/dem0n",
            description='Дамьян “dem0n” Христов — rifler, выступающий на европейской сцене и постепенно закрепляющийся в профессиональной среде. Его игра характеризуется уверенностью в дуэлях и стремлением к развитию. Участие в международных квалификациях и турнирах позволяет ему набирать опыт и повышать уровень игры.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="lauNX",
            real_name="Лауренциу Цырля",
            country_code="RO",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20761/launx",
            description='Лауренциу “lauNX” Цырля — один из наиболее известных игроков состава, ранее выступавший на HLTV-турнирах и демонстрировавший высокий потенциал. Его стиль игры сочетает агрессию и хорошую механику, что делает его важным элементом команды. Он уже имеет опыт игры против сильных соперников и способен показывать высокий уровень.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Krabeni",
            real_name="Кристиан Станчев",
            country_code="BG",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/22203/krabeni",
            description='Кристиан “Krabeni” Станчев — стабильный игрок состава, принимающий участие в региональных и международных турнирах. Его вклад заключается в выполнении ключевых ролей и поддержании структуры команды, что особенно важно для коллективов, находящихся в стадии развития.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="cmtry",
            real_name="Кристиян Митев",
            country_code="BG",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/22674/cmtry",
            description='Кристиан “cmtry” Митев — support-игрок, обеспечивающий дисциплину и порядок в игре команды. Его задачи включают помощь тиммейтам, контроль карты и участие в разменах. Такие игроки являются фундаментом команды, позволяя ей действовать более организованно.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="dziugss",
            real_name="Джюгас Степонавичюс",
            country_code="LT",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/23553/dziugss",
            description='Джюгас “dziugss” Степонавичюс — игрок, представляющий Литву на профессиональной сцене. Он участвует в европейских турнирах и квалификациях, набирая опыт и развиваясь как игрок. Его стремление к прогрессу и участие в командной игре делают его важной частью FUT Esports.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'fisher-college': [
        Player(
            nickname="AlekS",
            real_name="Александр Андерссон",
            country_code="SE",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/13298/aleks",
            description='Александр “AlekS” Андерссон — капитан Fisher College, который отвечает за структуру игры, координацию команды и принятие ключевых решений по ходу матча.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="TH0R",
            real_name="Торстейн Фридфиннссон",
            country_code="IS",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/12793/th0r",
            description='Торстейн “TH0R” Фридфиннссон — снайпер Fisher College, чья задача заключается в контроле ключевых позиций и создании преимущества за счёт точных первых убийств.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="ReFuZR",
            real_name="Нилс Гроот",
            country_code="NL",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19602/refuzr",
            description='Нилс “ReFuZR” Гроот — саппорт Fisher College, который помогает тиммейтам гранатами, страхует размены и создаёт комфортные условия для атаки и обороны.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="CrePoW",
            real_name="Милан Либбрехт",
            country_code="BE",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20429/crepow",
            description='Милан “CrePoW” Либбрехт — entry-fragger Fisher College, который первым врывается на позиции соперника и старается открывать раунды для своей команды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="corn",
            real_name="Томми Экхарт",
            country_code="US",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/22137/corn",
            description='Томми “corn” Экхарт — rifler Fisher College, который даёт команде стабильную огневую мощь и уверенно играет в разменах и клатч-ситуациях.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'magic': [
        Player(
            nickname="MaSvAl",
            real_name="Святослав Маско",
            country_code="BY",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19874/masval",
            description='Святослав “MaSvAl” Маско — rifler команды magic, который играет надёжно, помогает удерживать темп команды и стабильно вносит урон в ключевых разменах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="tENZY",
            real_name="Никита Коченюк",
            country_code="RU",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/24173/tenzy",
            description='Никита “tENZY” Коченюк — rifler команды magic, который усиливает состав в перестрелках и даёт команде дополнительную огневую мощь в середине и конце раунда.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="sFade8",
            real_name="Виталий Марушка",
            country_code="UA",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/22075/sfade8",
            description='Виталий “sFade8” Марушка — капитан magic, который координирует действия команды, задаёт общий рисунок игры и принимает важные решения в напряжённых раундах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="AW",
            real_name="Андрей Анисимов",
            country_code="RU",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/22076/aw",
            description='Андрей “AW” Анисимов — снайпер magic, который отвечает за дальние дуэли, контроль опасных углов и поиск первых преимуществ для команды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="mo0N",
            real_name="Абдурахим Иса",
            country_code="KZ",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/23858/mo0n",
            description='Абдурахим “mo0N” Иса — entry-fragger команды magic, который любит активные действия, часто идёт первым и старается вскрывать защиту соперника за счёт уверенных врывов.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'huns-esports': [
        Player(
            nickname="nin9",
            real_name="Есунтумур Гантулга",
            country_code="MN",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/15072/nin9",
            description='Есунтумур “nin9” Гантулга — rifler The Huns Esports, который помогает команде держать стабильный урон и уверенно играет в затяжных перестрелках.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="Bart4k",
            real_name="Баатархуу Батболд",
            country_code="MN",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19957/bart4k",
            description='Баатархуу “Bart4k” Батболд — entry-fragger The Huns Esports, который открывает пространство для команды и часто первым принимает на себя самые жёсткие дуэли.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="xerolte",
            real_name="Мунхтогтох Энхбат",
            country_code="MN",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20703/xerolte",
            description='Мунхтогтох “xerolte” Энхбат — rifler The Huns Esports, который хорошо чувствует темп игры и даёт составу уверенность в середине раунда.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="sk0R",
            real_name="Тэнгис Батжаргал",
            country_code="MN",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/18638/sk0r",
            description='Тэнгис “sk0R” Батжаргал — снайпер The Huns Esports, который способен делать разницу за счёт резких AWP-пиков и уверенного контроля карты.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="controlez",
            real_name="Унуделгэр Баасанжаргал",
            country_code="MN",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/21398/controlez",
            description='Унуделгэр “controlez” Баасанжаргал — капитан The Huns Esports, который отвечает за дисциплину команды, координацию действий и принятие тактических решений.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    'k27': [
        Player(
            nickname="kashl1d",
            real_name="Данила Дронов",
            country_code="RU",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/23686/kashl1d",
            description='Данила “kashl1d” Дронов — rifler K27, который помогает команде держать стабильный огневой уровень и надёжно играет в стандартных разменах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="relaxxie",
            real_name="Карим Мифтахов",
            country_code="RU",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/23684/relaxxie",
            description='Карим “relaxxie” Мифтахов — rifler K27, который усиливает состав в перестрелках и способен брать на себя важные клатч-эпизоды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="xeedo",
            real_name="Алексей Микулич",
            country_code="BY",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/22886/xeedo",
            description='Алексей “xeedo” Микулич — entry-fragger K27, который создаёт пространство для команды своими активными выходами и первым принимает бой.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="qw1nk1",
            real_name="Даниил Кабилов",
            country_code="RU",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/24725/qw1nk1",
            description='Даниил “qw1nk1” Кабилов — снайпер K27, который отвечает за контроль дальних дистанций и поиск важных первых фрагов для своей команды.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="X5G7V",
            real_name="Даниил Марышев",
            country_code="RU",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/19575/x5g7v",
            description='Даниил “X5G7V” Марышев — капитан K27, который руководит игрой команды, следит за тактической дисциплиной и старается держать состав собранным в тяжёлых матчах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],

    '9z': [
        Player(
            nickname="max",
            real_name="Максимилиано Гонсалес",
            country_code="UY",
            role=PlayerRoleEnum.IGL,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/12092/max",
            description='Максимилиано “max” Гонсалес — капитан 9z, который управляет темпом игры команды, отвечает за тактические коллы и держит состав собранным в напряжённых матчах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="dgt",
            real_name="Франко Гарсия",
            country_code="UY",
            role=PlayerRoleEnum.ENTRY,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/14736/dgt",
            description='Франко “dgt” Гарсия — entry-fragger 9z, известный агрессивным стилем и умением быстро вскрывать оборону соперника в начале раунда.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="meyern",
            real_name="Игнасио Майер",
            country_code="AR",
            role=PlayerRoleEnum.RIFLER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/14737/meyern",
            description='Игнасио “meyern” Майер — rifler 9z, который добавляет составу мощь в перестрелках и часто берёт на себя роль главного damage-дилера в сложных эпизодах.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="luchov",
            real_name="Лучиано Эррера",
            country_code="AR",
            role=PlayerRoleEnum.SUPPORT,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/20394/luchov",
            description='Лучиано “luchov” Эррера — саппорт 9z, который много работает на команду, грамотно использует utility и помогает выстраивать надёжную игру по карте.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
        Player(
            nickname="HUASOPEEK",
            real_name="Матиас Ибаньес Эрнандес",
            country_code="CL",
            role=PlayerRoleEnum.SNIPER,
            photo_url=None,
            hltv_url="https://www.hltv.org/stats/players/22613/huasopeek",
            description='Матиас “HUASOPEEK” Ибаньес Эрнандес — снайпер 9z, который контролирует пространство карты и способен переворачивать раунды точной стрельбой из AWP.',
            team_id=None,
            is_active=True,
            created_at=None,
            team=None,
        ),
    ],
}


async def sync_players(teams, s):

    for team in teams:
        new_players = main_players.get(team.slug, [])
        team_id = team.id
        print(f'team.slug: {team.slug} , team_id: {team_id} , team.id: {team.id}')

        result = await s.execute(select(Player).where(Player.team_id == team.id))
        db_players = result.scalars().all()

        new_nicknames = {player.nickname for player in new_players}


        for new_player in new_players:

            result = await s.execute(
                select(Player).where(Player.nickname == new_player.nickname)
            )
            existing = result.scalar_one_or_none()

            if existing:
                existing.team_id = team_id
                existing.real_name = new_player.real_name
                existing.country_code = new_player.country_code
                existing.role = new_player.role
                existing.photo_url = f'/static/photos/{team.slug}/{existing.nickname}.png'
                existing.description = new_player.description
                existing.hltv_url = new_player.hltv_url
                existing.is_active = True
            else:
                new_player.team_id = team_id
                new_player.photo_url = f'/static/photos/{team.slug}/{new_player.nickname}.png'
                new_player.is_active = True
                s.add(new_player)

        for db_player in db_players:
            if db_player.nickname not in new_nicknames:
                db_player.is_active = False

    
    await s.commit()


async def main():
    async with session() as s:
        result = await s.execute(select(Team))
        teams = result.scalars().all()

        await sync_players(teams, s)



if __name__ == '__main__':
    asyncio.run(main())