"""init

Revision ID: a28b2b1e3927
Revises: 
Create Date: 2026-04-02 18:30:15.775034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28b2b1e3927'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('region', sa.Enum('CIS', 'EU', 'NA', 'SA', 'ASIA', 'OCE', 'MENA', name='regionenum'), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('bo_type', sa.Enum('BO1', 'BO3', 'BO5', name='botypeenum'), nullable=False),
    sa.Column('stage', sa.Enum('GROUP_STAGE', 'QUARTER_FINAL', 'SEMIFINAL', 'FINAL', name='stageenum'), nullable=False),
    sa.Column('status', sa.Enum('ENDED', 'ONGOING', 'UPCOMING', name='matchstatus'), nullable=False),
    sa.Column('score_team1', sa.Integer(), nullable=False),
    sa.Column('score_team2', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('stream_url', sa.String(), nullable=True),
    sa.Column('match_page_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('team1_id != team2_id', name='check_teams_not_equal'),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('real_name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('role', sa.Enum('RIFLER', 'SNIPER', 'IGL', 'SUPPORT', 'ENTRY', name='playerroleenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('hltv_url', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('matches_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('map_order', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.Enum('DUST2', 'MIRAGE', 'ANUBIS', 'INFERNO', 'NUKE', 'ANCIENT', 'TRAIN', name='mapnameenum'), nullable=False),
    sa.Column('picked_by_team_id', sa.Integer(), nullable=True),
    sa.Column('score_team1', sa.Integer(), nullable=False),
    sa.Column('score_team2', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['picked_by_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_map_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Float(), nullable=False),
    sa.Column('deaths', sa.Float(), nullable=False),
    sa.Column('assists', sa.Float(), nullable=False),
    sa.Column('adr', sa.Float(), nullable=False),
    sa.Column('kast', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('hs_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_map_id'], ['matches_maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    op.drop_table('matches_maps')
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_table('teams')
    # ### end Alembic commands ###
